In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nltk as nk
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv(r"C:\Users\LENOVO\Desktop\sentiment mental\Combined Data.csv")

In [3]:
df

Unnamed: 0                                          statement   status
0               0                                         oh my gosh  Anxiety
1               1  trouble sleeping, confused mind, restless hear...  Anxiety
2               2  All wrong, back off dear, forward doubt. Stay ...  Anxiety
3               3  I've shifted my focus to something else but I'...  Anxiety
4               4  I'm restless and restless, it's been a month n...  Anxiety
...           ...                                                ...      ...
53038       53038  Nobody takes me seriously I’ve (24M) dealt wit...  Anxiety
53039       53039  selfishness  "I don't feel very good, it's lik...  Anxiety
53040       53040  Is there any way to sleep better? I can't slee...  Anxiety
53041       53041  Public speaking tips? Hi, all. I have to give ...  Anxiety
53042       53042  I have really bad door anxiety! It's not about...  Anxiety

[53043 rows x 3 columns]

In [4]:
df.head(10)

Unnamed: 0                                          statement   status
0           0                                         oh my gosh  Anxiety
1           1  trouble sleeping, confused mind, restless hear...  Anxiety
2           2  All wrong, back off dear, forward doubt. Stay ...  Anxiety
3           3  I've shifted my focus to something else but I'...  Anxiety
4           4  I'm restless and restless, it's been a month n...  Anxiety
5           5  every break, you must be nervous, like somethi...  Anxiety
6           6  I feel scared, anxious, what can I do? And may...  Anxiety
7           7    Have you ever felt nervous but didn't know why?  Anxiety
8           8  I haven't slept well for 2 days, it's like I'm...  Anxiety
9           9                 I'm really worried, I want to cry.  Anxiety

In [5]:
df.tail(10)

Unnamed: 0                                          statement   status
53033       53033  I'm an adult who can not sleep alone. So I'm 3...  Anxiety
53034       53034  Neighbours Hello  I’m haveing anxiety because ...  Anxiety
53035       53035  Oxazepam? Hey! I have been taking oxazepam 7,5...  Anxiety
53036       53036  someone help me think rationally I know I soun...  Anxiety
53037       53037  Lorazepam side effect/after effect In the last...  Anxiety
53038       53038  Nobody takes me seriously I’ve (24M) dealt wit...  Anxiety
53039       53039  selfishness  "I don't feel very good, it's lik...  Anxiety
53040       53040  Is there any way to sleep better? I can't slee...  Anxiety
53041       53041  Public speaking tips? Hi, all. I have to give ...  Anxiety
53042       53042  I have really bad door anxiety! It's not about...  Anxiety

In [6]:
len(df)

53043

In [7]:
df.shape

(53043, 3)

In [8]:
df.columns

Index(['Unnamed: 0', 'statement', 'status'], dtype='object')

In [9]:
df.describe()

Unnamed: 0
count  53043.000000
mean   26521.000000
std    15312.339501
min        0.000000
25%    13260.500000
50%    26521.000000
75%    39781.500000
max    53042.000000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53043 entries, 0 to 53042
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  53043 non-null  int64 
 1   statement   52681 non-null  object
 2   status      53043 non-null  object
dtypes: int64(1), object(2)
memory usage: 1.2+ MB


In [11]:
df.isnull().sum()

Unnamed: 0      0
statement     362
status          0
dtype: int64

In [12]:
((df.isnull().sum()/len(df))*100).round(2)

Unnamed: 0    0.00
statement     0.68
status        0.00
dtype: float64

In [13]:
df.dropna(inplace=True)


In [14]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [15]:
df.iloc[0,0]

'oh my gosh'

In [16]:
df['status'].value_counts()

status
Normal                  16343
Depression              15404
Suicidal                10652
Anxiety                  3841
Bipolar                  2777
Stress                   2587
Personality disorder     1077
Name: count, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X = df['statement']

In [19]:
y = df['status']

In [20]:
X_train, X_test, y_train, y_test = train_test_split (X,y, test_size=0.30, random_state=42)

In [21]:
X_train.shape

(36876,)

In [22]:
X_test.shape

(15805,)

In [23]:
y_train.shape

(36876,)

In [24]:
y_test.shape

(15805,)

# TFidf Vectorizer 

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [27]:
tf = TfidfVectorizer()

In [38]:
X_train_vect = tf.fit_transform(X_train)

In [39]:
X_test_vect = tf.transform(X_test)

In [30]:
X_test_vect.shape

(15805, 31611)

# Model fitting using random forest

In [32]:
from sklearn.ensemble import RandomForestClassifier

In [33]:
rf = RandomForestClassifier()

In [34]:
rf.fit(X_train_vect,y_train)

RandomForestClassifier()

In [40]:
y_pred = rf.predict(X_test_vect)

In [54]:
from sklearn.metrics import classification_report

In [58]:
print(classification_report(y_pred, y_test))

                      precision    recall  f1-score   support

             Anxiety       0.34      0.95      0.50       409
             Bipolar       0.26      0.98      0.41       218
          Depression       0.82      0.51      0.63      7381
              Normal       0.94      0.80      0.87      5884
Personality disorder       0.23      0.99      0.38        79
              Stress       0.19      1.00      0.32       151
            Suicidal       0.37      0.71      0.49      1683

            accuracy                           0.66     15805
           macro avg       0.45      0.85      0.51     15805
        weighted avg       0.79      0.66      0.69     15805



In [60]:
from sklearn.metrics import classification_report, confusion_matrix

In [62]:
print(confusion_matrix(y_pred, y_test))

[[ 387    2    5    4    0   10    1]
 [   1  214    2    0    0    1    0]
 [ 506  513 3739  258  215  508 1642]
 [ 231   75  365 4709   33   94  377]
 [   0    0    0    0   78    1    0]
 [   0    0    0    0    0  151    0]
 [   9   10  426   16    6   15 1201]]


# Hyperparameter

In [69]:
from sklearn.ensemble import RandomForestClassifier 
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint
from sklearn.metrics import accuracy_score


In [71]:
param_dist ={"n_estimators":randint(10,200),
             "max_depth":randint(3,20),
             "min_sample_split": randint(2,20),
             "min_samples_leaf": randint(1,20),
             "bootstrap":[True,False]}

In [75]:
random_search = RandomizedSearchCV(rf,param_distributions = param_dist,n_iter=20,cv=5,scoring='accuracy',random_state=42,n_jobs=-1)